In [9]:
import numpy as np
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,22,33,44,55]
l4=[66,77,88,99,100]
l11=[111,112,113,114,115]
l21=[1116,1117,1118,1119,11110]
l31=[5511,5522,5533,5544,5555]
l41=[5566,5577,5588,5599,15500]
a=np.array([l1,l2,l3,l4,l11,l21,l31,l41])

In [43]:
a.shape

(8, 5)

In [48]:
b=a.shape[1]
c=a.shape[0]

In [53]:
for col in range(b):
    for row in range(c):
        if col==3 and row == 3:
            print(a[row,col])
            a[row,col]=9999999
print(a)
            
        

99
[[      1       2       3       4       5]
 [      6       7       8       9      10]
 [     11      22      33      44      55]
 [     66      77      88 9999999     100]
 [    111     112     113     114     115]
 [   1116    1117    1118    1119   11110]
 [   5511    5522    5533    5544    5555]
 [   5566    5577    5588    5599   15500]]


In [88]:
lst1=[1,2,3,4,5,6]
lst2=[11,22,33,44,55,66]
ffff=np.array([lst1,lst2])
dd=np.reshape(ffff,(4,3))

dd


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [91]:
website='http://docs.scipy.org/doc/numpy/reference/'
import webbrowser
webbrowser.open(website)


True

In [12]:
ary1=([1,2,3,4,5])
ary2=([100,200,300,400,500])
cond=([True,True,True,False,False])

ans=[(a_val if cond else b_val) for a_val,b_val,cond in zip(ary1,ary2,cond)]
arr=np.array([ans,[1,2,3,4,5]])

In [14]:
arr.sum()

921

In [17]:
ary2=np.array([100,200,300,400,500,100,200,300,400,500])
np.unique(ary2)

array([100, 200, 300, 400, 500])

AttributeError: 'list' object has no attribute 'sum'

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [50]:
for row in range(c):
    for col in range(b):
        print(f'Row={row} and column={col} and value is {a[row,col]}')

Row=0 and column=0 and value is 1
Row=0 and column=1 and value is 2
Row=0 and column=2 and value is 3
Row=0 and column=3 and value is 4
Row=0 and column=4 and value is 5
Row=1 and column=0 and value is 6
Row=1 and column=1 and value is 7
Row=1 and column=2 and value is 8
Row=1 and column=3 and value is 9
Row=1 and column=4 and value is 10
Row=2 and column=0 and value is 11
Row=2 and column=1 and value is 22
Row=2 and column=2 and value is 33
Row=2 and column=3 and value is 44
Row=2 and column=4 and value is 55
Row=3 and column=0 and value is 66
Row=3 and column=1 and value is 77
Row=3 and column=2 and value is 88
Row=3 and column=3 and value is 99
Row=3 and column=4 and value is 100
Row=4 and column=0 and value is 111
Row=4 and column=1 and value is 112
Row=4 and column=2 and value is 113
Row=4 and column=3 and value is 114
Row=4 and column=4 and value is 115
Row=5 and column=0 and value is 1116
Row=5 and column=1 and value is 1117
Row=5 and column=2 and value is 1118
Row=5 and column=

(8, 5)

AttributeError: 'int' object has no attribute 'shape'

NameError: name 'a' is not defined